stages:
    - build
    - test
    - test_deploy
    - deploy

include:
    - local: ".gitlab/ci/build.yml"
    - local: ".gitlab/ci/test.yml"
    - local: ".gitlab/ci/docs.yml"
    - local: ".gitlab/ci/deploy.yml"
